apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videodownloader-pvc
  namespace: videodownloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi